name: telegram-downloader-bot
services:
  - name: app
    docker:
      image: python:3.11-slim
    ports:
      - port: 8080
        http:
          paths:
            - /
    env:
      - name: TELEGRAM_BOT_TOKEN
        value: "7863008338:AAGoOdY4xpl0ATf0GRwQfCTg_Dt9ny5AM2c"
      - name: PORT
        value: "8080"
      - name: PYTHONUNBUFFERED
        value: "1"
    regions:
      - fra
    instance:
      type: nano
    scaling:
      min: 1
      max: 1
    health_checks:
      http:
        path: /health
        port: 8080
        interval: 30
        timeout: 5
